version: '2.4'
services:
  sflcore-app:
    image: sflcore
    env_file:
      - ../../../.env
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING.DATASOURCE.URL=jdbc:mysql://sflcore-mysql:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
    ports:
      - ${API_PORT}:8080
    depends_on:
      sflcore-mysql:
        condition: service_healthy
  sflcore-mysql:
    extends:
      file: mysql.yml
      service: sflcore-mysql
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
volumes:
  mysqldata:
