version: '2.4'
services:
  sflcore-mysql:
    image: mysql:8.0.20
    volumes:
      - 'mysqldata:/var/lib/mysql/'
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: 'exit 0'
